import { eq } from 'drizzle-orm';
import { nanoid } from 'nanoid';
import sharp from 'sharp';
import { consola } from 'consola';
import { CommunError, ERR } from '../../common/errors/index.ts';
import type { StoreDb } from '../../infrastructure/db/index.ts';
import type { StorageDriver } from '../../infrastructure/storage/index.ts';
import { media, type Media } from './schema.ts';

export const MAX_UPLOAD_BYTES = 20 * 1024 * 1024; // 20 MB

/** Closed allowlist: images, PDF and common office documents. Never executables. */
export const ALLOWED_MIME = new Set([
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/gif',
  'image/svg+xml',
  'application/pdf',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.oasis.opendocument.text',
  'application/vnd.oasis.opendocument.spreadsheet',
]);

/** Raster formats that get webp variants (svg and gif are kept as-is). */
const VARIANT_MIME = new Set(['image/jpeg', 'image/png', 'image/webp']);
const VARIANT_WIDTHS = [320, 768, 1280] as const;

const sanitizeFilename = (name: string) =>
  name.replace(/[^a-zA-Z0-9._-]/g, '_').slice(-120) || 'file';

export interface UploadInput {
  filename: string;
  mime: string;
  bytes: Uint8Array;
  alt?: string;
}

/**
 * Validate and store an upload: original object first, media row second.
 * Image variants are generated by an internal async task (fire-and-forget
 * from the route) — no external queue, one instance = one collectivité.
 */
export async function uploadMedia(
  db: StoreDb,
  storage: StorageDriver,
  input: UploadInput,
): Promise<Media> {
  if (!ALLOWED_MIME.has(input.mime)) {
    throw new CommunError(ERR.INVALID_STATE, `type de fichier non autorisé: ${input.mime}`);
  }
  if (input.bytes.byteLength === 0 || input.bytes.byteLength > MAX_UPLOAD_BYTES) {
    throw new CommunError(
      ERR.INVALID_STATE,
      `taille de fichier invalide (max ${MAX_UPLOAD_BYTES / 1024 / 1024} Mo)`,
    );
  }

  const filename = sanitizeFilename(input.filename);
  const originalKey = `${nanoid(10)}/${filename}`;
  await storage.put(originalKey, input.bytes, input.mime);

  return db
    .insert(media)
    .values({
      filename,
      mime: input.mime,
      size: input.bytes.byteLength,
      alt: input.alt ?? null,
      driver: storage.kind,
      objects: { original: originalKey, variants: {} },
    })
    .returning()
    .get();
}

/** Internal async task: derive webp variants and attach them to the media row. */
export async function generateImageVariants(
  db: StoreDb,
  storage: StorageDriver,
  mediaId: string,
  bytes: Uint8Array,
): Promise<void> {
  const row = db.select().from(media).where(eq(media.id, mediaId)).get();
  if (!row || !VARIANT_MIME.has(row.mime)) return;

  const objects = row.objects as { original: string; variants: Record<string, string> };
  const dir = objects.original.split('/')[0];
  try {
    for (const width of VARIANT_WIDTHS) {
      const variant = await sharp(bytes)
        .resize({ width, withoutEnlargement: true })
        .webp({ quality: 80 })
        .toBuffer();
      const key = `${dir}/variants/w${width}.webp`;
      await storage.put(key, new Uint8Array(variant), 'image/webp');
      objects.variants[`w${width}`] = key;
    }
    db.update(media).set({ objects }).where(eq(media.id, mediaId)).run();
  } catch (error) {
    // The original stays perfectly usable without variants — log, don't fail.
    consola.warn(`génération des variantes échouée pour ${mediaId}:`, error);
  }
}

/** Delete the row AND every stored object (original + variants) — spec media-storage. */
export async function removeMedia(db: StoreDb, storage: StorageDriver, id: string): Promise<void> {
  const row = db.select().from(media).where(eq(media.id, id)).get();
  if (!row) throw new CommunError(ERR.NOT_FOUND, `média introuvable: ${id}`);
  const objects = row.objects as { original: string; variants: Record<string, string> };
  await storage.remove([objects.original, ...Object.values(objects.variants ?? {})]);
  db.delete(media).where(eq(media.id, id)).run();
}
