import { defineHandler } from 'nitro';
import { HTTPError } from 'h3';
import { consola } from 'consola';
import { CommunError, generateImageVariants, uploadMedia } from '@commun/core';
import { requireSession, useCore } from '../../../services/context.ts';

/**
 * Media upload (multipart form-data, field `file`, optional `alt`). Session
 * required. Webp variants are generated by an internal async task after the
 * response — the original is immediately usable.
 */
export default defineHandler(async (event) => {
  const req = event.req as unknown as Request;
  requireSession(req);
  const core = useCore();

  const form = await req.formData().catch(() => null);
  const file = form?.get('file');
  if (!form || !(file instanceof File)) {
    throw new HTTPError({ status: 400, message: 'multipart attendu avec un champ "file"' });
  }

  const bytes = new Uint8Array(await file.arrayBuffer());
  try {
    const row = await uploadMedia(core.db, core.storage, {
      filename: file.name,
      mime: file.type,
      bytes,
      alt: (form.get('alt') as string | null) ?? undefined,
    });
    // Internal async task — deliberately not awaited.
    void generateImageVariants(core.db, core.storage, row.id, bytes).catch((error) =>
      consola.warn('variantes:', error),
    );
    return row;
  } catch (error) {
    if (error instanceof CommunError) {
      throw new HTTPError({ status: 400, message: error.message });
    }
    throw error;
  }
});
